version: "3.7"
services:
  app:
    build:
      args:
        user: dave
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: wassessment
    container_name: wassessment-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - wassessment

  nginx:
    image: nginx:alpine
    container_name: wassessment-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - wassessment

networks:
  wassessment:
    driver: bridge